build site:
  image: node:latest
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - build

unit test:
  image: node:latest
  stage: test
  script:
    - npm install --progress=false
    - npm run test

deploy:
  image: alpine
  stage: deploy
  script:
    - apk add --no-cache rsync openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_PRIVATE_KEY" >> ~/.ssh/id_dsa
    - chmod 600 ~/.ssh/id_dsa
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
    - rsync -avvr --delete --exclude=.env "$PWD/build/" root@dev.medienhaus.udk-berlin.de:/var/www/html