name: Deploy to dev.

on:
  push:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      matrix_base_url:
        description: Matrix Server URL
        required: true
        default: 'https://dev.medienhaus.udk-berlin.de'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: cp ./.github/stubs/config.dev.json ./src/config.json

      - uses: actions/setup-node@v2.1.5
        with:
          node-version: '15'

      - run: npm clean-install

      # If this was a manually triggered deploy we may replace the Matrix base URL configuration variable via GitHub's UI
      - if: ${{ github.event_name == 'workflow_dispatch' }}
        name: Update Matrix base URL in config.json
        uses: datamonsters/replace-action
        with:
          files: 'src/config.json'
          replacements: 'https://dev.medienhaus.udk-berlin.de=${{github.event.inputs.matrix_base_url}}'

      - run: npm run build

      - uses: up9cloud/action-rsync@v1.1
        env:
          HOST: dev.medienhaus.udk-berlin.de
          KEY: ${{secrets.DEPLOY_SSH_KEY}}
          TARGET: /var/www/html/
          VERBOSE: true
          USER: root
          PORT: 22
          ARGS: --recursive --update --delete --compress --exclude=/.git/
          SSH_ARGS: '-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no'
          SOURCE: ./build/
